### ISSUE TITLE
ios 8 / swift integration

### ISSUE THREAD

**Issue by sidshekar** [simonkim/spine-spritekit#4]
HI. Is there an example with swift integration of spine in Spritekit?

**Comment by rclayborn** [comment]
This is what I posted on the Spine Web site.... I hope this helps.
Dec, 1 2014 using the newest updates:
Ok, I worked out the best possible solution until the Sprite runtimes are written in swift. Use this link to find the runtimes in Objective-c. 
https://github.com/mredig/SGG_SKSpineImport. This is the only Libary now I could get to work.
Copy over the "SpineImporter" file and all it's content. While uploading that file onto your Swift project Xcode will ask you for a bridging head. Check YES. then go to the bridging file and type this #import "SpineImporter.h". from there you can use the files inside of your swift project. Below is the code to get the Spine animation to work inside of swift. One last think, copy over your Spine files and the Atlas file that goes to your Spine file(total4 files). Make sure that you have changed the names in the code below to reflect your own files. This should get you started. 

//put in GameScene or intended animation file.
import SpriteKit

class GameScene: SKScene {
    var mo = SGG_Spine()

```
override func didMoveToView(view: SKView) {
    backgroundColor = SKColor.whiteColor()

    mo.skeletonFromFileNamed("skeleton", andAtlasNamed:"MOCharacter", andUseSkinNamed:nil)
    mo.position = CGPointMake(self.size.width * 0.5, self.size.height * 0.3);
    mo.runAnimation("animation", andCount: -1)
    mo.queuedAnimation = "animation"
    mo.queueIntro = 0.1;
    mo.zPosition = 20;
    mo.xScale = 0.4;
    mo.yScale = 0.4;
    mo.zRotation = 0.0
    addChild(mo)

      }

override func touchesBegan(touches: NSSet, withEvent event: UIEvent) {
    for touch: AnyObject in touches {
        let location = touch.locationInNode(self)
```

//            self.inputBegan(location) // uncomment if you want to use touches

```
    }
}
```

**Comment by sidshekar** [comment]
OK great. Thanks. I'll try and implement it. :)

Regards.

Siddharth.

**Comment by sidshekar** [comment]
Hi,

After a long time I thought I will play around with spritekit, swift and
spine.

When I add let hero = SGG_Spine() to the mainmenu scene I get the error.

Undefined symbols for architecture arm64:

  "_OBJC_CLASS_$_SGG_Spine", referenced from:

      __TMaCSo9SGG_Spine in MainMenuScene.o

ld: symbol(s) not found for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see
invocation)

The header has the following import

#import "SpineImporter/SpineImport.h"

Any idea how to get around this problem?

I had a similar problem while importing GlyphDesigner into spine and I just
had to add the glyphdeigner.a file and now the problems is gone. Am I
missing a library somewhere?

Thanks

Siddharth.

**Comment by sidshekar** [comment]
Ok I think I fixed that part. Instead of importing the whole importer folder I just copied the filesover and at the I dont get the error. But when it builds I get images with red crosses on them. 

        hero.skeletonFromFileNamed("player", andAtlasNamed: "player", andUseSkinNamed: nil)
        hero.position = CGPoint(x: viewSize.width/2, y: viewSize.height/2)
        hero.runAnimation("runCycle", andCount: -1)
        addChild(hero)

I am using the same files I used in my cocos2d-x project from here. https://github.com/sidshekar/cc2dx33_wp8Game

**Comment by sidshekar** [comment]
OK. ANother updade. Got the images to show by adding all the atlas images into a player.atlas FOLDER and importing it into spritekit but still the animation is not playing. In the last time also the animation was not getting played and images where also not showing so guess I am one step closer. :D

**Comment by sidshekar** [comment]
Hmm... I am really stuck now. Looks like hero.runAnimation("runCycle", andCount: -1) doesnt have any effect!!!

**Comment by sidshekar** [comment]
WORKING!!! in swift. You missed out to include hero.activateAnimations()  in the udpdate function!!!!... Now it is working :D

**Comment by sidshekar** [comment]
Hi,

I am using your runtime in my book iOS Game Developement and would like to
thank you in the acknowledgement. Just to confirm your name is Simon and
not Michael???

Pls revert asap as book is almost into production.

Rgds,

Siddharth.

**Comment by mredig** [comment]
Just to clarify, if you are using https://github.com/simonkim/spine-spritekit, that is not mine. That is Simon's. If you are using https://github.com/mredig/SGG_SKSpineImport then that is mine.

**Comment by sidshekar** [comment]
Yes. I am using sgg_ version. But in the mail (to/from)why does it say
simonkim?!??

**Comment by mredig** [comment]
This is an issue thread on Simon's spine implementation. I believe my runtime was just listed as an alternative to an issue you had?

**Comment by sidshekar** [comment]
Could you send a mail from your alternate mail address so that simon is not
in the loop??

**Comment by mredig** [comment]
I didn't see an email on your profile to email you, but you can contact me here: http://redeggproductions.com/contact.html

**Comment by sidshekar** [comment]
Ok. Just wanted to inform that I have used your runtime for the ios game
development and thanked you for it in the acknowledgement for it. :)

**Comment by sidshekar** [comment]
The book will be published by packt I will send you a link once the book is
out for your reference.

**Comment by mredig** [comment]
Well thank you! I look forward to seeing it!

**Comment by simonkim** [comment]
Good to know that it's sorted out. ;-)
- Simon

**Comment by sidshekar** [comment]
Yes, it wouldnt be right if I had it the otherway around.

Regards,

siddharth.
