### ISSUE TITLE
Separate repositories

### ISSUE THREAD

**Issue by victoraldecoa** [simonkim/spine-spritekit#5]
Hi,
I intend to build a UIKit renderer library, to use it in a project which has iOS 6 as a requirement.
I'm basing most of my code in spine-spritekit and I've noticed it's already separated in an Objective-C wrapper library and SpriteKit specific classes.

So I thought maybe it would be better to separate the wrapper files in a "spine-obj-c" repo and add it as a pod requirement in both our projects. So than it would be easier for us both to keep the spine-obj-c up-to-date and also other people would be able to create other renderers more easily (e.g OpenGL, Metal?). And of course, more people using it means more Pull Requests with enhancements and bug fixes. It's a big win-win I think.

**Comment by simonkim** [comment]
Hi @victoraldecoa 

Thank you for suggestion and it sounds good if you mean putting "spine-spritekit/*.[hm]" in a separate repo, say "spine-obj-c" as you suggested. and link it as a submodule to spine-spritekit.

Let me see if there is a straightforward way doing so without messing up the commit history for both repos.

Thanks,
Simon

**Comment by victoraldecoa** [comment]
I actually meant using CocoaPods instead of linking it as a submodule. There are many advantages of using CocoaPods, such as managing dependencies, versions, etc.

**Comment by simonkim** [comment]
@victoraldecoa How would it sound if you initiate turning this project into CocoaPods? Maybe you can even think of taking over this project... 

I'm actually not Gaming or serious 2D animation kind of person compared to the folks interested in this project. But you maybe are more of that kind.

What do you think?

**Comment by victoraldecoa** [comment]
@simonkim that sounds good!
Well, I guess I'll create a fork then and make the changes I said, and I'll claim the Pod as the responsible for managing the versions with CocoaPods. Than you keep appearing as the project creator and can continue managing the Pull Requests if you want. And if you like my fork you can pull the changes to this main repo.

Thanks!

**Comment by victoraldecoa** [comment]
Hi @simonkim !

Just letting you know that I just finished organising everything (yep, took a lot of work) and created both pods. They are hosted at:

https://github.com/victoraldecoa/objective-spine
https://github.com/victoraldecoa/spine-spritekit

And they are already pointed at CocoaPods master repo. These are the results when running the command pod search Spine:

```
-> ObjectiveSpine (1.0.0)
   Objective-C Wrapper for spine-c
   pod 'ObjectiveSpine', '~> 1.0.0'
   - Homepage: https://github.com/victoraldecoa/objective-spine
   - Source:   https://github.com/victoraldecoa/objective-spine.git
   - Versions: 1.0.0 [master repo]


-> Spine-Cocos2d (1.7.08)
   2D skeletal animation runtime for Spine
   pod 'Spine-Cocos2d', '~> 1.7.08'
   - Homepage: http://esotericsoftware.com/
   - Source:   https://github.com/EsotericSoftware/spine-runtimes.git
   - Versions: 1.7.08, 1.6.13 [master repo]


-> SpineSpriteKit (1.0.0)
   Spine renderer for SpriteKit
   pod 'SpineSpriteKit', '~> 1.0.0'
   - Homepage: https://github.com/victoraldecoa/spine-spritekit
   - Source:   https://github.com/victoraldecoa/spine-spritekit.git
   - Versions: 1.0.0 [master repo]
```

I hope I can work on a UIKit or OpenGL renderer version soon, using ObjectiveSpine. :)
Thank you very much for this great project! And please let me know if there's anything I should change, such as license, putting your name more clearly on readme, or anything. You can send me with pull requests or directly via e-mail or on this thread.

Best regards!
